### PR TITLE
Updated the formatting of the use cases

### PR DESCRIPTION
**Pull request by noise404**

### CODE REVIEW

**Review by ak74ub — COMMENTED** [review]
Use Case # 4 requires change of wording. Verbiage of Use Case #4 needs to be clearer that this is on the physical device. Titles have been changed. Organization of use cases have also changed.

**Review by ak74ub — COMMENTED** [review]
Possibly consider to change learning to garden use case title to monitoring soil moisture levels to have better continuity. For LED check we can say Monitor levels using physical visual aid.

**Comment by noise404** [comment]
Updated the learning to garden use case, changing title and position. Haven't updated LED use case. Don't agree with that title. Can be a conversation in person.

**Review by ak74ub — APPROVED** [review]
Changes made have improved organization and titles made capture use cases well.

**Pull request merged**
